### ISSUE TITLE
再陽性をカウントしないようロジックを変更したい

### ISSUE THREAD

**Issue by yuukis** [daisuke19891023/covid19-yamanashi-scraping#63]
## 改善詳細 / Details of Improvement
- 再陽性患者が [新型コロナウイルス感染症の県内における発生状況](https://www.pref.yamanashi.jp/koucho/coronavirus/info_coronavirus_prevention.html#Patients) の表に入ったことにより再陽性患者が陽性患者数にカウントされてしまい、県で発表している感染者と数が合わなくなっている

## 期待する見せ方・挙動 / Expected behavior
- 再陽性患者は「陽性患者数」および「陽性患者の属性」に入らないようにしたい

参照
https://github.com/covid19-yamanashi/covid19/pull/54

**Comment by okadai23** [comment]
再陽性がカウントされないよう修正しました。

**Comment by yuukis** [comment]
> 再陽性がカウントされないよう修正しました。

ご対応ありがとうございました！
クローズします。
