### ISSUE TITLE
患者情報を新フォーマットのページから取得する

### ISSUE THREAD

**Issue by okadai23** [daisuke19891023/covid19-yamanashi-scraping#68]
divで囲われていない素のhtmlからテキスト読み取りを行う

**Comment by imabari** [comment]
患者情報スクレイピングできました
https://imabari.hateblo.jp/entry/2020/06/11/165653

**Comment by okadai23** [comment]
@imabari 
ありがとうございます！ブログのコードを参考にしたら患者情報のスクレイピングが出来るようになりました！

**Comment by imabari** [comment]
60件までのpatientsからpatients_summaryを作るとdata.jsonとの差が多いのですが原因わかりますか？
https://github.com/covid19-yamanashi/covid19/blob/development/data/data.json

patients_summaryはこちらで作成
https://github.com/imabari/covid19-data/blob/master/yamanashi/main.py

**Comment by okadai23** [comment]
フォーマット変更が発生するまでは、patientsとpatients_summaryで利用する日付項目にずれがありました
- patients_summary:発生判明日でサマリを取得
- patients:リリース日を表示
61件目以降はリリース日の項目がなくなってしまっているため、今のフォーマットで集計を行うと`data.json`とのずれが発生してしまいます。
リリース日と発生判明日のどちらを利用するべきかを現在本家のIssueとして確認しています。
https://github.com/covid19-yamanashi/covid19/issues/80

**Comment by imabari** [comment]
承知しました
リリース日より発生判明日の方に変更しているところが多いですね
山梨県のデータは変換するのが難しいのでPDFのときは途中でやめました

**Comment by imabari** [comment]
data.jsonのpatientsの4/16に「山」と「女」が文字コードが違う漢字が入ってます
