### ISSUE TITLE
PCR検査件数・電話相談件数・陽性者の状況のオープンデータ

### ISSUE THREAD

**Issue by imabari** [daisuke19891023/covid19-yamanashi-scraping#77]
PCR検査件数・電話相談件数・陽性者の状況のオープンデータで公開されています

新型コロナウイルスPCR検査件数
https://www.pref.yamanashi.jp/koucho/coronavirus/documents/pcr.xlsx

新型コロナウイルス電話相談件数
https://www.pref.yamanashi.jp/koucho/coronavirus/documents/soudan.xlsx

新型コロナウイルス陽性者の状況
https://www.pref.yamanashi.jp/koucho/coronavirus/documents/yousei.xlsx

**Comment by imabari** [comment]
Excelからdata.json作成しています
https://github.com/imabari/covid19-data/blob/master/yamanashi/main_excel.py

**Comment by okadai23** [comment]
反応できていなくてすみませんでした！提供いただいたpyファイルを参考に処理を修正いたします！

**Comment by keitasuzukijp** [comment]
@imabari @daisuke19891023 
ありがとうございます！自動更新が止まってしまってちょうどIssueたててご相談しようとしていました…。
今は @yuukis さんが手動で更新してくれています。
お手数をおかけしますが、何卒よろしくお願いいたします。

**Comment by keitasuzukijp** [comment]
データの更新は時差があるようですね…。
11/11 12:00時点で最終最終更新が11/9でした。

**Comment by okadai23** [comment]
11/9にソースの改修を行ったので、元データに対して更新があれば、それを検知して再度更新されるかと思います。ただ、csvからのデータ生成は未対応なので、今週末に対応したいと思います

**Comment by keitasuzukijp** [comment]
@daisuke19891023 そうでしたか！ありがとうございますー！

**Comment by okadai23** [comment]
@imabari 
遅くなりましたが提示いただいたコードをベースにExcelからのdata.json生成に対応しました！
ご提示いただきありがとうございました！

**Comment by imabari** [comment]
xlrdがxlsxの読み込みが非対応になったためエラーが発生します
https://xlrd.readthedocs.io/en/latest/changes.html

xlsxファイルを読み込む場合は、engine="openpyxl"で指定してください
pd.read_excel('tmp.xlsx', engine="openpyxl")
